AllCops:
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'tinderb.gemspec'
